site_name: {{cookiecutter.project_name}}
site_url: https://github.com/{{cookiecutter.github_username}}
site_description: {{cookiecutter.project_short_description}}
site_author: {{cookiecutter.full_name}}
site_dir: html

plugins:
  - search
  - mkapi
  - awesome-pages
  - gen-files:
      scripts:
        - gen_pages.py

theme:
    name: material

nav:
  - index.md
  - ... | readme.md
  - ... | scenarios/**/*.md
  - API: mkapi/api/{{cookiecutter.package_name}}
  - Tests: mkapi/tests/tests

