repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: fix-encoding-pragma
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
        files: .*\.py
    -   id: mixed-line-ending
    -   id: name-tests-test
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
        - id: mypy
-   repo: local
    hooks:
    -   id: black-formatter
        name: black-formatter
        stages: [commit]
        language: system
        entry: nox -s black
        types: [python]
        pass_filenames: false
-   repo: local
    hooks:
    -   id: flake8-lint
        name: flake8-lint
        stages: [commit]
        language: system
        entry: nox -s lint
        types: [python]
        pass_filenames: false
-   repo: local
    hooks:
    -   id: pytest-cov
        name: pytest-cov
        stages: [commit]
        language: system
        entry: nox -s tests
        types: [python]
        pass_filenames: false
-   repo: local
    hooks:
    -   id: test-docs
        name: test-docs
        stages: [push]
        language: system
        entry: nox -s test-docs
        types: [python]
        pass_filenames: false
-   repo: local
    hooks:
    -   id: documentation
        name: documentation
        stages: [push]
        language: system
        entry: nox -s api-docs
        types: [python]
        pass_filenames: false
-   repo: local
    hooks:
    -   id: uml-diagram
        name: uml-diagram
        stages: [commit]
        language: system
        entry: nox -s uml
        types: [python]
        pass_filenames: false
