[tool.poetry]
name = "{{cookiecutter.package_name}}"
version = "{{cookiecutter.version}}"
description = "{{cookiecutter.project_short_description}}"
authors = ["{{cookiecutter.full_name}} <{{cookiecutter.email}}>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "7.1.1"
pytest-cov = "^3.0.0"
pre-commit = "^2.18.1"
flake8 = "^4.0.1"
mypy = "^0.942"
isort = "^5.10.1"
black = {version = "^22.3.0", allow-prereleases = true}
flake8-docstrings = "^1.6.0"
xdoctest = "^1.0.0"
Pygments = "^2.11.2"
pep8-naming = "^0.12.1"
darglint = "^1.8.1"
pytest-html = "^3.1.1"
pdoc3 = "^0.10.0"
cookiecutter = "^1.7.3"
pylint = "^2.13.4"
graphviz = "^0.19.1"
pydot = "^1.4.2"
flake8-secure-coding-standard = "^1.2.1"
nox = "^2022.1.7"
flake8-todos = "^0.1.5"
flake8-logging-format = "^0.6.0"
flake8-builtins = "^1.5.3"
flake8-pytest-style = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | docs
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --color=yes --cov=src --cov-fail-under=100 --cov-report term-missing --doctest-modules --cov-config=setup.cfg"
testpaths = [
    "tests",
    "src"
]
python_files = ["*_test.py"]
python_functions = ["test_*"]
render_collapsed = true

[tool.mypy]
warn_return_any = false
warn_unused_configs = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = [
    "{{cookiecutter.package_name}}"
]
follow_imports = "silent"
strict_optional = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true
ignore_missing_imports = true
