name: Check Code standards

on:
  push:

jobs:
  set-up-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install ruff and cookiecutter
        run: |
          apt update && apt install -y python3-pip && pip install ruff cookiecutter
      -
        name: run cookiecutter
        run: |
          cookiecutter . --no-input
      -
        name: lint tests
        run: |
          cd python-project-example
          echo 'Code check tests:'
          ruff check
          echo 'Code format tests:'
          ruff format --diff
