name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y python3-pip docker-compose
        pip3 install cookiecutter
    - name: Generate project files with cookiecutter
      run: cookiecutter --no-input .
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and test
      uses: docker/build-push-action@v5
      with:
        context: ./python-project-example
        file: ./Dockerfile
        push: false

